apiVersion: apps/v1
kind: Deployment
metadata:
  name: esma-api
  labels:
    app: esma-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esma-api
  template:
    metadata:
      labels:
        app: esma-api
    spec:
      containers:
        - name: esma-api
          image: quay.io/gmagnotta/esma-api
          env:
            - name: QUARKUS_INFINISPAN_CLIENT_SERVER_LIST
              value: 'datagrid-nodes:11222'
            - name: QUARKUS_INFINISPAN_CLIENT_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: datagrid
                  key: user
            - name: QUARKUS_INFINISPAN_CLIENT_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datagrid
                  key: password
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: esma-api
  labels:
    app: esma-api
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  selector:
    app: esma-api
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: esma-api
  labels:
    app: esma-api
spec:
  to:
    kind: Service
    name: esma-api
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
