apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: esma-ui
message: This is an OpenShift template to deploy esma-ui.
metadata:
  name: esma-ui
  annotations:
    description: "esma-ui Template"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: esma-ui
  data:
    backend-url: ${BACKEND_URL}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: esma-ui
    labels:
      app: esma-ui
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: esma-ui
    template:
      metadata:
        labels:
          app: esma-ui
      spec:
        containers:
          - name: esma-ui
            image: quay.io/gmagnotta/esma-ui
            env:
              - name: BACKEND_URL
                valueFrom:
                  configMapKeyRef:
                    name: esma-ui
                    key: backend-url
            readinessProbe:
              exec:
                command:
                - "/bin/bash"
                - "-c"
                - 'curl --noproxy ''*'' -is ''http://localhost:8080/health'' | grep -iq ''"status": "UP"'''
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8778
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 60
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: esma-ui
    labels:
      app: esma-ui
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
      - name: 8778-tcp
        protocol: TCP
        port: 8778
        targetPort: 8778
    selector:
      app: esma-ui
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: esma-ui
    labels:
      app: esma-ui
  spec:
    to:
      kind: Service
      name: esma-ui
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
- description: Backend url
  name: BACKEND_URL
  value: 'http://esma-api:8080'